/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/QeZQG99tkw4
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function HeroTest() {
  return (
    <section className="w-full py-16 md:py-24 lg:py-32 relative">
      <div className="absolute inset-0 bg-[url('/placeholder.svg')] bg-cover bg-center bg-no-repeat z-0 opacity-20" />
      <div className="absolute inset-0 bg-gradient-to-r from-gray-900 to-transparent z-10 opacity-50" />
      <div className="container px-4 md:px-6 relative z-20">
        <div className="grid gap-4 md:gap-6">
          <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl text-white">
            Discover Our Innovative Solutions
          </h1>
          <p className="max-w-[700px] text-gray-50 md:text-xl dark:text-gray-300">
            Explore our cutting-edge products and services designed to revolutionize your business.
          </p>
        </div>
      </div>
    </section>
  )
}
