/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Il2Wl4jHJga
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function team() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet Our Team</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our talented team of experts is dedicated to delivering exceptional results for our clients.
            </p>
          </div>
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 mt-12">
          <div className="bg-white rounded-lg shadow-lg dark:bg-gray-950">
            <div className="relative">
              <img
                alt="Team Member"
                className="w-full h-64 object-cover rounded-t-lg"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-bold">John Doe</h3>
              <p className="text-gray-500 dark:text-gray-400">CEO</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-lg dark:bg-gray-950">
            <div className="relative">
              <img
                alt="Team Member"
                className="w-full h-64 object-cover rounded-t-lg"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-bold">Jane Smith</h3>
              <p className="text-gray-500 dark:text-gray-400">CTO</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-lg dark:bg-gray-950">
            <div className="relative">
              <img
                alt="Team Member"
                className="w-full h-64 object-cover rounded-t-lg"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-bold">Michael Johnson</h3>
              <p className="text-gray-500 dark:text-gray-400">Lead Designer</p>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-lg dark:bg-gray-950">
            <div className="relative">
              <img
                alt="Team Member"
                className="w-full h-64 object-cover rounded-t-lg"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
            <div className="p-4">
              <h3 className="text-xl font-bold">Sarah Lee</h3>
              <p className="text-gray-500 dark:text-gray-400">Marketing Manager</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
